version: '2.1'
services:
  mongo:
    image: mongo:rc-xenial
    restart: always
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5673:5672"
      - "15672:15672"
    stdin_open: true
    tty: true
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  producer:
    build: producer
    restart: always
    volumes:
      - ./producer/src/:/project
    command: python3 main.py
    env_file:
      - config.env
    links:
      - rabbitmq
      - api
    depends_on:
      rabbitmq:
        condition: service_healthy
    stdin_open: true
    tty: true

  worker:
    build: worker
    restart: always
    volumes:
      - ./worker/src/:/project
    command: python3 main.py
    env_file:
      - config.env
    links:
      - rabbitmq
      - mongo
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    stdin_open: true
    # tty: true

  api:
    build: api
    restart: always
    volumes:
      - ./api/src/:/project/
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --error-logfile - api
    ports:
      - 8000:8000
    links:
      - mongo:mongo
    depends_on:
      - mongo
